# -*- coding: utf-8 -*-
"""Lógica de programação.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13dKl_UQ_sI5h69nj2eYVsZjMM99ERPlS

## Lógica de programação com Python
"""

nome = 'Bruna'

idade = 28

print(f'O nome é {nome} e sua idade é {idade} anos.')



"""# Criando minha primeira função"""

def saudacao():
  nome = input('Qual o seu nome? ')
  print(f'Olá,{nome}')

saudacao()

def nome_completo():
 primeiro_nome = input('Qual seu primeiro nome? ')
 sobrenome = input('Qual seu sobrenome? ')
 nome_inteiro = primeiro_nome + ' ' + sobrenome
 print(nome_inteiro)

nome_completo()

"""# Paramêtros"""

nome = 'Luiza'

def saudacao_com_parametro(nome_da_pessoa):
  print(f'Olá, {nome_da_pessoa}.')

saudacao_com_parametro(nome)



"""# Condicional

"""

idade = 20

def verifica_se_pode_dirigir(idade):
  if idade >=18:
    print(f'Tem permissão para dirigir.')
  else:
    print('Não tem permissão para dirigir.')

verifica_se_pode_dirigir(idade)

"""# Convertendo tipo Inteiro

"""

def verifica_se_pode_dirigir_sem_parametro():
  idade = input('Qual dua idade? ')
  idade = int(idade)
  
  if idade >=18:
    print(f'Tem permissão para dirigir.')
  else:
    print('Não tem permissão para dirigir.')

verifica_se_pode_dirigir_sem_parametro()

def habilitacao():
 idade = input('Qual sua idade? ')
 idade = int(idade)
 if idade >= 18:
   print('Pode tirar habilitação')
 else:
   tempo = 18 - idade
   print(f'Calma... espere {tempo} ano(s) para tirar habilitação')

habilitacao()



"""# Lista

"""

idade = 22
idade

type(idade)

idades = [18, 22, 15, 50]
type(idades)

idades[2]

idades = [18, 22, 15, 50]
#         0   1   2   3
#         0  -3  -2  -1

idades[1]

idades[0:3]

idades[1:]

idades[-1]

idades[-2]



"""# Laços e Loops

"""

idades

#for fora da função

def verifica_se_pode_dirigir(idade):
  if idade >=18:
    print(f'{idade} anos, tem permissão para dirigir.')
  else:
    print(f'{idade} anos, não tem permissão para dirigir.')

for idade in idades:
  verifica_se_pode_dirigir(idade)

def verifica_se_pode_dirigir(idades):
  for idade in idades:
    if idade >=18:
      print(f'{idade} anos, tem permissão para dirigir.')
    else:
      print(f'{idade} anos, não tem permissão para dirigir.')

verifica_se_pode_dirigir(idades)



"""# Booleano

"""

idade = 18
idade >= 18

idade = 15
idade >= 18

permissoes = []
idades = [20, 14, 40]

def verifica_se_pode_dirigir(idades, permissoes):
  for idade in idades:
    if idade >=18:
      permissoes.append(True)
    else:
      permissoes.append(False)

verifica_se_pode_dirigir(idades, permissoes)

permissoes

for permissao in permissoes:
  if permissao == True:
    print('Tem permissão para dirirgir.')
  else:
    print('Não tem permissão para dirigir')

"""# Tipos em uma lista

"""

lista = ['Bruna', 28,  True, '18']

for elemento in lista:
  print(f'O elemento {elemento} é do tipo: ', type(elemento))

"""# Import"""

from random import randrange, seed

seed(11)

randrange(0, 11)

notas_matematica = []

for notas in range(8):
    notas_matematica.append([randrange(0,11)])

notas_matematica

len(notas_matematica)

"""# Matplotlib"""

import matplotlib.pyplot as plt

x = list(range(1,9))
y = notas_matematica
plt.plot(x, y, marker='o')
plt.title('Notas de Matemática')
plt.xlabel('Provas')
plt.ylabel('Notas')
plt.show()

